services:
  db:
    image: mysql:5.7
    container_name: device-mysql
    restart: always
    tty: true
    working_dir: /mysql_device
    environment:
      MYSQL_ROOT_PASSWORD: 'urubu100'
      MYSQL_PASSWORD: 'urubu100'
      MYSQL_DATABASE: 'device'
    ports:
      - '3306:3306'
    volumes:
      - /var/opt/mssql
      - ./schemas:/var/lib/mysql:rw
      - ./scripts/sql:/docker-entrypoint-initdb.d/
    networks:
      - main_network
  java:
    image: gabrieldasilvadev/device-java:2.1.6
    container_name: device-java
    restart: always
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - db
    entrypoint: ['java', '-jar', 'devices-1.0-SNAPSHOT-jar-with-dependencies.jar']
    networks:
      - main_network
 

volumes:
  schemas: {}

networks:
  main_network: {}
